# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mathematics-for-ML-and-DS',
                'doc_host': 'https://m-01101101.github.io',
                'git_url': 'https://github.com/m-01101101/mathematics-for-ML-and-DS',
                'lib_path': 'mathematics_for_ML_and_DS'},
  'syms': { 'mathematics_for_ML_and_DS.core': { 'mathematics_for_ML_and_DS.core.foo': ( 'core.html#foo',
                                                                                        'mathematics_for_ML_and_DS/core.py')}}}
